# Generated by Django 3.2.16 on 2023-01-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P1ComponentCompositionOfUnstableCondensate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_components', models.FloatField()),
                ('molar_mass_of_the_component', models.FloatField()),
                ('total_molar_mass', models.FloatField()),
                ('chromatograph_mass', models.FloatField()),
                ('calculated_mass', models.FloatField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'p1_component_composition_of_unstable_condensate',
                'managed': False,
            },
        ),
    ]
