# Generated by Django 3.2.16 on 2023-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_oks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P10ProtokolKGN',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_mass_of_the_component', models.FloatField()),
                ('difference', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p10_protokol_kng',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P2ComponentCompositionOfGas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_content_of_components', models.FloatField()),
                ('molar_mass_of_the_component', models.FloatField()),
                ('total_molar_mass', models.FloatField()),
                ('chromatograph_mass', models.FloatField()),
                ('calculated_mass', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p2_component_composition_of_gas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P3DeterminationOfTheComponentOfGas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_content_of_components', models.FloatField()),
                ('molar_mass_of_the_component', models.FloatField()),
                ('total_molar_mass', models.FloatField()),
                ('chromatograph_mass', models.FloatField()),
                ('calculated_mass', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p3_determination_of_the_component_of_gas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P4GasCompositionToTheProtocol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_content_of_components', models.FloatField()),
                ('molar_mass_of_the_component', models.FloatField()),
                ('total_molar_mass', models.FloatField()),
                ('chromatograph_mass', models.FloatField()),
                ('calculated_mass', models.FloatField()),
                ('content_of_the_component', models.FloatField()),
                ('proportion_of_the_component', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p4_gas_composition_to_the_protocol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P5DeterminationOfTheComponentComposition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_content_of_components', models.FloatField()),
                ('molar_mass_of_the_component', models.FloatField()),
                ('total_molar_mass', models.FloatField()),
                ('chromatograph_mass', models.FloatField()),
                ('calculated_mass', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p5_determination_of_the_component_composition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P6CompositionOfGasOutput',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_content_of_components', models.FloatField()),
                ('molar_mass_of_the_component', models.FloatField()),
                ('total_molar_mass', models.FloatField()),
                ('chromatograph_mass', models.FloatField()),
                ('calculated_mass', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p6_composition_of_gas_output',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P7CompositionOfGas10c',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_content_of_components', models.FloatField()),
                ('molar_mass_of_the_component', models.FloatField()),
                ('total_molar_mass', models.FloatField()),
                ('chromatograph_mass', models.FloatField()),
                ('calculated_mass', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p7_composition_of_gas_10c',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P8CompositionOfTheCondensate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cylinder_1506', models.FloatField()),
                ('cylinder_1641', models.FloatField()),
                ('average_value', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p8_composition_of_the_condensate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P9ComponentOfTheSeparationGas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('molar_content_of_components', models.FloatField()),
                ('molar_mass_of_the_component', models.FloatField()),
                ('total_molar_mass', models.FloatField()),
                ('chromatograph_mass', models.FloatField()),
                ('calculated_mass', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p9_component_of_the_separation_gas',
                'managed': False,
            },
        ),
    ]
