# Generated by Django 3.2.16 on 2023-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_oks', '0002_p10protokolkgn_p2componentcompositionofgas_p3determinationofthecomponentofgas_p4gascompositiontothep'),
    ]

    operations = [
        migrations.CreateModel(
            name='NrProd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nr_prod_c1_c4_p4', models.FloatField()),
                ('nk_prod_c5_c6', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nr_prod',
                'managed': False,
            },
        ),
    ]
