# Generated by Django 3.2.16 on 2023-01-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_raports', '0002_mer_per_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ser_per_month',
            options={'managed': False},
        ),
    ]
