# Generated by Django 3.2.16 on 2023-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeclossesOne',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('v', models.FloatField()),
                ('pn', models.FloatField()),
                ('tn', models.FloatField()),
                ('zn', models.FloatField()),
                ('press_pk', models.FloatField()),
                ('tk', models.FloatField()),
                ('zk', models.FloatField()),
                ('v_op', models.FloatField()),
                ('ng_prod', models.FloatField()),
                ('ng_nl', models.FloatField()),
                ('xg_prod', models.FloatField()),
                ('n', models.FloatField()),
                ('pn_op', models.FloatField()),
                ('mol', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teclosses_one',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeclossesTree',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('v_pr', models.FloatField()),
                ('p_pr', models.FloatField()),
                ('t_pr', models.FloatField()),
                ('z_pr', models.FloatField()),
                ('b', models.FloatField()),
                ('ni', models.FloatField()),
                ('xr_prod', models.FloatField()),
                ('pr_op', models.FloatField()),
                ('device', models.CharField(max_length=255)),
                ('v_p', models.FloatField()),
                ('tau', models.FloatField()),
                ('xrr_prod', models.FloatField()),
                ('n', models.FloatField()),
                ('pr_pot', models.FloatField()),
                ('pr_pr', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teclosses_three',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeclossesTwo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('qgr_sh', models.FloatField()),
                ('ng_prod', models.FloatField()),
                ('ng_pl', models.FloatField()),
                ('xg_prod', models.FloatField()),
                ('pgr_sh', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teclosses_two',
                'managed': False,
            },
        ),
    ]
