# Generated by Django 3.2.16 on 2023-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_rtp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading30P1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_one', models.FloatField()),
                ('num_two', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meter_readings_30P_1',
                'managed': False,
            },
        ),
    ]
