# Generated by Django 3.2.16 on 2023-02-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_rtp', '0002_meterreading30p1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadingAll',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meter_p34', models.FloatField()),
                ('meter_30p1', models.FloatField()),
                ('meter_10c1', models.FloatField()),
                ('meter_10c4', models.FloatField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meter_readings_all',
                'managed': False,
            },
        ),
    ]
