# Generated by Django 3.2.16 on 2023-02-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_rtp', '0003_meterreadingall'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingcalcOne',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('aij', models.FloatField()),
                ('bij', models.FloatField()),
                ('tauij', models.FloatField()),
                ('a_ij', models.FloatField()),
                ('mi', models.FloatField()),
                ('q_yp', models.FloatField()),
                ('t_type', models.CharField(max_length=255)),
                ('t_aij', models.FloatField()),
                ('t_bij', models.FloatField()),
                ('t_tauij', models.FloatField()),
                ('t_a_ij', models.FloatField()),
                ('t_mi', models.FloatField()),
                ('t_q_yp', models.FloatField()),
                ('date_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'recyclingcalc_one',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
