# Generated by Django 3.2.16 on 2023-02-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_rtp', '0004_recyclingcalcone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingcalcOneTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='recyclingcalcone',
            options={'managed': False},
        ),
    ]
