# Generated by Django 3.2.16 on 2023-02-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_rtp', '0005_auto_20230222_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recyclingcalconetime',
            options={'managed': False},
        ),
    ]
