# Generated by Django 3.2.16 on 2023-02-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asrmb_rtp', '0006_alter_recyclingcalconetime_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recyclingcalconetime',
            table='recyclingcalc_one_time',
        ),
    ]
